AWSTemplateFormatVersion: 2010-09-09
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: com.penguinwan.quiz

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Action: 's3:GetObject'
            Effect: Allow
            Resource: !Sub 'arn:aws:s3:::${S3Bucket}/*'
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
      Bucket: !Ref S3Bucket

  CloudFrontOriginAccessIdentity:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref S3Bucket

  CloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        CustomErrorResponses:
        - ErrorCode: 403 # not found
          ResponseCode: 404
          ResponsePagePath: /error.html
        DefaultCacheBehavior:
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          TargetOriginId: s3origin
          ForwardedValues:
            QueryString: 'false'
            Headers:
              - Access-Control-Request-Headers
              - Access-Control-Request-Method
              - Origin
            Cookies:
              Forward: none
          ViewerProtocolPolicy: allow-all
        DefaultRootObject: index.html
        Enabled: true
        Origins:
        - DomainName: 
            !Join ['', [!Ref 'S3Bucket', '.s3.', !Ref 'AWS::Region', '.amazonaws.com']]
          Id: s3origin
          S3OriginConfig:
            OriginAccessIdentity: 
              !Join ['', ['origin-access-identity/cloudfront/', !Ref CloudFrontOriginAccessIdentity]]
        PriceClass: PriceClass_All
        ViewerCertificate: 
          CloudFrontDefaultCertificate: true

Outputs:
  WebsiteURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt CloudFrontDistribution.DomainName
        - /index.html
    Description: URL for website hosted on S3